"""Test data IDs - generated by test-data-prep.sql
Run after test-data-prep.sql"""

# animal_id mappings
A1 = '5a0a6491-76e9-11f1-84ef-52be1da5a590'  # 金毛 lost 静安公园 (lat=31.2280,lng=121.4470)
A2 = '5a0b53c0-76e9-11f1-84ef-52be1da5a590'  # 金毛 lost 静安公园 (lat=31.2285,lng=121.4475)
A3 = '5a0c5f79-76e9-11f1-84ef-52be1da5a590'  # 拉布拉多 lost 浦东金桥
A4 = '5a0d1fd0-76e9-11f1-84ef-52be1da5a590'  # 萨摩耶 found 虹口四川北路
A5 = '5a0df046-76e9-11f1-84ef-52be1da5a590'  # 土狗 lost 徐汇衡山路
A6 = '5a0ec69c-76e9-11f1-84ef-52be1da5a590'  # 土狗 lost 徐汇衡山路 (距A5 100m)
A7 = '5a0f9a7a-76e9-11f1-84ef-52be1da5a590'  # 边牧 lost 长宁中山公园
A8 = '5a1052bd-76e9-11f1-84ef-52be1da5a590'  # 柴犬 found 闵行莘庄
A9 = '5a11691b-76e9-11f1-84ef-52be1da5a590'  # 中华田园猫 lost 静安公园 (同A1位置)
A10 = '5a122d7c-76e9-11f1-84ef-52be1da5a590'  # 英短 claimed 普陀长寿路

# user_ids
USER1 = 'utestu01-0001-0000-0000-000000000020'  # 测试-李明 (A1主人)
USER2 = 'utestu02-0001-0000-0000-000000000021'  # 测试-王小红 (A3主人)
USER3 = 'utestu03-0001-0000-0000-000000000022'  # 测试-张小华
USER4 = 'utestu04-0001-0000-0000-000000000023'  # 测试-陈建国
USER5 = 'utestu05-0001-0000-0000-000000000024'  # 测试-刘秀英
ADMIN = 'utestadm-0001-0000-0000-000000000088'  # 测试管理员

# nose_vector_ids
NOSE_A1 = 'c11857b0-b9fc-4c5d-a637-6bc0a4c0b4d4'
NOSE_A3 = '90c621be-9e00-46f2-8810-c712fad9fca7'
NOSE_A4 = '9e29799b-9db6-4013-9950-f15bd4edac3a'
NOSE_A5 = '45ddf234-4079-4ead-af14-bf209d4f88f4'
NOSE_A7 = 'e12fe133-b197-42f4-a47f-a576fe1ac704'
NOSE_A8 = 'fd266196-312f-4c81-82ce-684813d7a600'
NOSE_A9 = '54b5ba97-d659-4106-a7d6-01f94f9c0762'
NOSE_A10 = '4ca583b6-f59a-48c9-96c8-2381617aee3a'

# locations (lat, lng) — Shanghai
LOC_A1 = (31.2280, 121.4470)  # 静安公园
LOC_A2 = (31.2285, 121.4475)  # 静安公园 ~80m
LOC_A3 = (31.2550, 121.5950)  # 浦东金桥
LOC_A4 = (31.2650, 121.4980)  # 虹口四川北路
LOC_A5 = (31.1950, 121.4350)  # 徐汇衡山路
LOC_A6 = (31.1958, 121.4358)  # 徐汇衡山路 ~100m
LOC_A7 = (31.2200, 121.4180)  # 长宁中山公园
LOC_A8 = (31.1100, 121.3820)  # 闵行莘庄
LOC_A9 = (31.2280, 121.4470)  # 静安公园 (同A1)
LOC_A10 = (31.2500, 121.3950)  # 普陀长寿路